Class User.Test
{

Parameter ASSTRING As STRING = "some_name";

Parameter ASSTRINGWITHERROR As STRING = 1234;

Parameter ASINTEGER As INTEGER = 1234;

Parameter ASINTEGERWITHERROR As INTEGER = "text";

Parameter ASBOOLEAN As BOOLEAN = 1;

Parameter ASBOOLEANWITHERROR As BOOLEAN = "true";

Parameter ASCOSEXPRESSION As COSEXPRESSION = "$ZVersion";

Parameter ASCLASSNAME As CLASSNAME = "User.Test";

}