
const bridge = require('./bridge.js')


const which = "CLS,COS,INT,XML,BAS,CSS,HTML,JAVA,JAVASCRIPT,MVBASIC,SQL,PYTHON";
bridge.START(which);

const arr = which.split(',');
var attrlist = {};
for (var index in arr) {
	const moniker = arr[index];
	const ret = bridge.GETLANGUAGEATTRINFO_OLD(moniker);	
	attrlist[arr[index]] = ret;
}

console.log('// <--- START')
console.log("// The following section is generated by makeattributesarray.js");
console.log('var attributes = {};');
for (var moniker in attrlist) {
	console.log('attributes["' + moniker + '"] = ' + JSON.stringify(attrlist[moniker]) + ';');
}
console.log('// END --->')

console.log('');
console.log('** Paste the preceding output into bridge.js, over the existing section');
